// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3EQPVha1HnuyTuBJzpvvfliHOXYfDF4',
    appId: '1:132333038544:web:99870e1ac6dff38da3e7d5',
    messagingSenderId: '132333038544',
    projectId: 'identicare-c3f80',
    authDomain: 'identicare-c3f80.firebaseapp.com',
    storageBucket: 'identicare-c3f80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4Gj9gHy9K6tF2gEmmAj17FTwzPmxw-4',
    appId: '1:132333038544:android:f45da256114af182a3e7d5',
    messagingSenderId: '132333038544',
    projectId: 'identicare-c3f80',
    storageBucket: 'identicare-c3f80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBszac5ri_Iy_181GlEiRmNbsErX4RxL5s',
    appId: '1:132333038544:ios:85cdcca601359d26a3e7d5',
    messagingSenderId: '132333038544',
    projectId: 'identicare-c3f80',
    storageBucket: 'identicare-c3f80.appspot.com',
    iosBundleId: 'com.example.identicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBszac5ri_Iy_181GlEiRmNbsErX4RxL5s',
    appId: '1:132333038544:ios:fdc818a48e8346eaa3e7d5',
    messagingSenderId: '132333038544',
    projectId: 'identicare-c3f80',
    storageBucket: 'identicare-c3f80.appspot.com',
    iosBundleId: 'com.example.identicare.RunnerTests',
  );
}
